### ISSUE TITLE
Team name textdraws alignment and size

### ISSUE THREAD

**Issue by khalidahmedshalabi** [KHKKhalid/SAMPBulletproof#10]
- This: http://prntscr.com/7u0unk
- The team names on match scoreboard textdraws (over money bar) doesn't look cool when you make a team with 6 characters length, they need to be a little bit smaller: http://prntscr.com/7u10rw.

Images provided by https://github.com/ApplePieLife

**Comment by Whitetigerswt** [comment]
``` cpp

TextDrawAlignment(td, 2);
```

**Comment by khalidahmedshalabi** [comment]
dfe65296c556cbafc0d989092e2498881c15d529
