### ISSUE TITLE
Problem(s) within /war command

### ISSUE THREAD

**Issue by A-Gebrel** [KHKKhalid/SAMPBulletproof#11]
Well, as a start : http://prntscr.com/7u166u

As you see, The command input was /war DASDAS ASDASD
DASDAS didn't show up, I thought, Probably some mistake with format or something.

I started a round and I was surprised to see this : http://prntscr.com/7u16on

I thought that textdraws are completely fucked up but once I did /teamname 0 DASDAS
the textdraws were fixed and ASDASD in-round textdraw (bottom) got fixed magically.
(( http://prntscr.com/7u1kmh ))

(The problem isn't related to alignment)
(Tested the /match command and didn't face this)

**Comment by A-Gebrel** [comment]
Alright, upon changing the sscanf params, The problem got fixed.
http://prntscr.com/7u1mel

**Comment by khalidahmedshalabi** [comment]
Make a pull request with the changes.
