### ISSUE TITLE
Better practice for version checker repeated checks

### ISSUE THREAD

**Issue by khalidahmedshalabi** [KHKKhalid/SAMPBulletproof#14]
Currently, this is the code that starts up the version checker script

``` C++
InitVersionChecker(timer, moreinfo)
{
    #if defined PRE_RELEASE_VERSION
    #pragma unused timer
    #pragma unused moreinfo
    VersionCheckerStatus = false;
    #else
    if(timer)
    {
        SetTimer("ReportServerVersion", 1 * 60 * 60 * 1000, true);
    }
    if(moreinfo)
    {
        HTTP(1, HTTP_GET, VERSION_CHECKER_FORCEUSER_URL, "", "ForceUserToUseNewest");
    }
    VC_ConnectionFailures = 0;
    HTTP(0, HTTP_GET, VERSION_CHECKER_VERSION_URL, "", "SaveVersionInStr");
    #endif
}
```

More closely, this

``` C++
SetTimer("ReportServerVersion", 1 * 60 * 60 * 1000, true);
```

This keeps repeating the version checks to see whether it's up to date or not over time. However I'm not much happy with it being in a timer like this. I'm not quite sure what could be better though. I have a few suggestions
- Check under OnPlayerConnect (not every time though, maybe once every 15 new player connections or so...)
- Check when the last player in the server disconnects (i.e when the server is left empty).
- ...?

I feel more comfortable with the second option (i.e OnPlayerDisconnect: last player leaves). What do you think?

**Comment by A-Gebrel** [comment]
Well, I think first one is better.
What if a player keeps logging in and out, It would be even worse then the current checking.
so I guess first one seems proper.

**Comment by khalidahmedshalabi** [comment]
First one? Do you mean the timer method? @ApplePieLife

**Comment by khalidahmedshalabi** [comment]
@Whitetigerswt I'd like to hear from you.

**Comment by A-Gebrel** [comment]
@KHKKhalid I mean the OnPlayerConnect method once each x players, but, that's also not a good idea.

I could call 7 tcw's on a raw and cancel them all if I don't feel like playing.
So OnPlayerConnect way is pretty much same as OnPlayerDisconnect however, Players connect to the server for a reason. (and they might disconnect from the server/s for any reason).

Personally, I can't say one of the methods are  better than the other. They are almost the same, Using current method with a bit more modification would seem proper.

If you really think it's a bad suggestion to keep current one, then monitor the time taken to reach x players and the time taken for them all to disconnect, I'm quite sure it will be way less time than the timer you are using above, however, You can't really expect players to play 24/7.

Lets make a bit of fast compare.

-- Current method: once an hour.
-- Using OnPlayerConnect with players count check.
Lets say they are going to play a tcw.
so 5-10 mins for players joining + 72 mins [9 rounds x 8 mins] on worst scenario of a tcw.
-- Using OnPlayerDisconnect:
??? player might connect and stay afk for hours for no reason. and they might connect and leave for no reason.

so It's either OnPlayerConnect with checks of players (or - if I may suggest - when a tcw is end/over and 7 rounds were played atleast)

**Comment by khalidahmedshalabi** [comment]
Well, you totally misunderstood things. @ApplePieLife 

**OnPlayerConnect** 
I will not check version every time it is called as I said I will do the checks once every 5 to 10 _OnPlayerConnect_ calls.

**OnPlayerDisconnect**
I will not check version every time it is called. I will only check version when the LAST player leaves (e.g 1/40) and then server is empty (i.e 0/X).

**Comment by A-Gebrel** [comment]
@KHKKhalid That's what I had in mind.
my calculation of OnPlayerConnect are based that you choose a check of 6+ players online, I don't really think I misunderstood anything.

the OnPlayerDisconnect issue I had in my mind. Server 0/40 > I connect 1/40 > Disconnect 0/40 (server checks version), Lets say I did that once each 10 mins, nonsense ? some people connect and stay online for hours then they disconnect.
So in some cases, OnPlayerDisconnect might take mins to be called over and over and in others it might take hours (or even days) depending on the player.

edit: I wish you consider the suggestion of checking version on when a tcw/cw is over when 7 rounds atleast had been played.

**Comment by khalidahmedshalabi** [comment]
I've already thought about this but that's not very smart either @ApplePieLife

**Comment by Whitetigerswt** [comment]
I would just do it when the server starts, tbh, don't know why you need this on a timer in the first place. you don't need to check for updates except when the server starts. thats how the AC does it, hasn't really ever been an issue there.

but if you have to, i'd do it in onplayerdisconnect. HTTP calls are threaded so it won't slow down anything. even if it did, 0 players are connected so who cares?

``` cpp
So in some cases, OnPlayerDisconnect might take mins to be called over and over and in others it might take hours (or even days) depending on the player.
```

So? All servers become empty at least once a day.

**Comment by khalidahmedshalabi** [comment]
Yeah, exactly @Whitetigerswt. As I said, I feel more comfortable to using OnPlayerDisconnect but I was kinda jumbled up and just needed someone to promote it for me :stuck_out_tongue:

> don't know why you need this on a timer in the first place. 

I want server owners to get and listen to updates QUICKER.
