### ISSUE TITLE
Flow in security

### ISSUE THREAD

**Issue by A-Gebrel** [KHKKhalid/SAMPBulletproof#20]
So, We were playing a tcw on our server when a guy came and started to ban us.

```
[20:50:38] {FFFFFF}ThatBoyCBUG {FF3035}has banned {FFFFFF}[H] {FF3035}| Reason: {FFFFFF}why so ez
[20:50:38] {FFFFFF}[H] {757575}has disconnected [{FFFFFF}Banned{757575}]
[20:50:39] <[GPB]Apex> (0) hopefully
[20:50:41] <NiNJaHz> (1) xD
[20:50:46] <sataNello7> (4) ff
[20:50:48] <sataNello7> (4) dont
[20:50:50] <sataNello7> (4) do
[20:50:52] <sataNello7> (4) that
[20:50:55] {FFFFFF}[GPB]SmokinAce {FF3035}has spawned as: {FFFFFF}Alpha
[20:50:57] <FroG.> (5) who the hell is this kido satanello?
[20:51:01] <sataNello7> (4) frog
[20:51:01] <ThatBoyCBUG> (2) Tell him to turn off his vpn.
[20:51:02] <[GPB]SmokinAce> (6) dont ban him
[20:51:03] <sataNello7> (4) he's italian but
[20:51:06] <sataNello7> (4) idk who is he
[20:51:08] <NiNJaHz> (1) mate that H is a tryhard
[20:51:09] <ThatBoyCBUG> (2) and I might be soft.
[20:51:09] Server closed the connection.
```

He connected and the msg didn't get sent, He banned me without rcon login nor having admin level, I've flushed the database few mins before it.

**Comment by A-Gebrel** [comment]
http://prntscr.com/7vcycs
@KHKKhalid @Whitetigerswt 
I see your scripting skills improved >;D

**Comment by khalidahmedshalabi** [comment]
There's no way to get admin level from nowhere in this gamemode (unless it's an edited version ofc). Are you sure he wasn't logged into rcon in anyway (_it should announce it on the chat though_)? Check your server log for something like this `RCON (In-Game): Player #0 (HIS_NAME) has logged in.`. Also open _admin_command_log.txt_ and search for his name to see if he used any of the gamemode admin commands.

**Comment by khalidahmedshalabi** [comment]
> http://prntscr.com/7vcycs

Someone is just fooling you...this is not possible.

**Comment by khalidahmedshalabi** [comment]
Check `OnRconLoginAttempt` in _bulletproof.pwn_

**Comment by A-Gebrel** [comment]
@KHKKhalid I've tested it on my server and it worked, after restarting it it didn't (ayy,lmao)
I've went on another server and tested it and it didn't work.
Still doesn't explain how the player was able to ban us without admin level and how he connected without connect message.

**Comment by khalidahmedshalabi** [comment]
Upload your database, server logs and admin_command_log.txt @ApplePieLife

**Comment by A-Gebrel** [comment]
@KHKKhalid 
I've flushed everything after first time he was reported.

Edit: I wish you mark this for further investigation because I'm quite sure this isn't all some random bug.

**Comment by khalidahmedshalabi** [comment]
I can't help then as well as I really couldn't reproduce anything of what you reported. You're claiming that he bypassed OnPlayerConnect and OnRconLoginAttempt which is impossible AFAIK, and then that guy made fun of you in that chat image you sent.. you're just being trolled there I think?

**Comment by A-Gebrel** [comment]
@KHKKhalid I wouldn't have reported it if it just happened to them.
that chatlog is mine, I banned the guy and he reconnected and started to ban us.
I thought that ban might be bugged or something but players reported they want unban.

# 

I've tested it on localhost, Started the server tried a false rcon login and it did kick me after 2nd fail try with no level given.
Connected again and restarted the server. (using rcon gmx)
After restert, I tried to rcon login with wrong password, the funny part. It didn't say anything about success rcon login but it did show "Rcon logged in ThatBoyCBUG" on /admins.
So, the the problem got something to do with restart (atleast with me).
When I closed the server and started it, the problem didn't show up.

Server Log : http://pastebin.com/WTErMYAw

**Comment by khalidahmedshalabi** [comment]
What's wrong? Players stay logged into rcon after GMX, that's normal...

**Comment by A-Gebrel** [comment]
@KHKKhalid Why do I keep forgeting this things while testing???

Alright, Walking by that, Compared to the admin_command_log I've sent you @ evolve.
The admin_command_log saved the commands used after restart by me, and it does the same on the log I've sent you, except that player, all his commands simply didn't show up.

returning to first logs, The player still connected without sending a connect message and as you said, 

> What's wrong? Players stay logged into rcon after GMX, that's normal...

So he had to rcon login again (which he didn't have) and the message of success login weren't sent aswell.

I highly doubt that this is all a combination of a restart bug and lucky player.

edit: he either found a flow in the gamemode to use commands he doesn't have access to, or he had access to our host (and that's the most likely way in my mind atm as you are saying there is no flow in security)

**Comment by khalidahmedshalabi** [comment]
Everything seems ridiculous here. You were just trolled by other server admins and players. Prove me wrong with a real evidence (i.e full server logs or a video reproducing the same bug), could you?

**Comment by KHKKhalid** [comment]
Issue will remain open in case of finding anything.
