### ISSUE TITLE
GetWeaponIDFromModelID undefined on gta v gun switch

### ISSUE THREAD

**Issue by shendlaw** [KHKKhalid/SAMPBulletproof#24]
when i set gtav_gunswitch on this_core i get that GetWeaponIDFromModelID in bulletproof.pwn is undefined.

**Comment by khalidahmedshalabi** [comment]
I remember commenting that function GetWeaponID... out; I'm sure I haven't removed it. So try to find it in one of the modules (probably weaponshot.inc or common.inc) and remove the commenting! Tell me if you don't find it.

**Comment by shendlaw** [comment]
done with common.inc

**Comment by shendlaw** [comment]
#if GTAV_SWITCH_MENU != 0
GetWeaponIDFromModelID(modelid)
{
...
}
#endif
