### ISSUE TITLE
AC Implementation

### ISSUE THREAD

**Issue by Whitetigerswt** [KHKKhalid/SAMPBulletproof#29]
I really wonder what you're waiting for...

**Comment by khalidahmedshalabi** [comment]
Busy. Undoubtedly, it will be on the next major release.

**Comment by Whitetigerswt** [comment]
Indeed, I'll make a new branch on here and try and implement it soon, very soon.

**Comment by khalidahmedshalabi** [comment]
You fixed your ac for linux, didn't you?

**Comment by khalidahmedshalabi** [comment]
Okay that's cool.

**Comment by khalidahmedshalabi** [comment]
https://github.com/KHKKhalid/Bulletproof-Gamemode/milestones/AC%20feast

**Comment by VIRUXE** [comment]
Is there a fix being worked on for the AC on Linux? Since there is no official way to ask for support for anything related to the AC this was the only place I could ask this.

@Whitetigerswt I've sent you 2 PM's via sa-mp forums. Hope you could read them.

**Comment by Whitetigerswt** [comment]
Yes there is.

**Comment by khalidahmedshalabi** [comment]
You might leave a comment there too http://www.samp-ac.com/ @viruxe

**Comment by VIRUXE** [comment]
I though about it but then after reading the comments and seeing no replies I thought that it wouldn't make a difference.
It just would be nice to atleast know that someone is aware of the issue.
