### ISSUE TITLE
Lag at arena 1 (weed farm)

### ISSUE THREAD

**Issue by shendlaw** [KHKKhalid/SAMPBulletproof#30]
When we play arena with id 1 (weed farm one) everyone gets fps drops

**Comment by khalidahmedshalabi** [comment]
I've never seen this in bulletproof gm. No one ever reported it to me either. Do you experience this on the original gamemode, or only your edit? Maybe you changed something on your edited version.

```
HostName: [KHK] ~ Server (Host Location: Germany)
Address:  5.230.139.110:8888
Players:  0 / 25
Ping:     114
Mode:     Bulletproof 0.1-RC2
Language: MURDER
```

**Comment by shendlaw** [comment]
i've seen it in both..

**Comment by khalidahmedshalabi** [comment]
Okay this is a weird bug... I can't figure out why it happens now
