### ISSUE TITLE
Bug or what?

### ISSUE THREAD

**Issue by shendlaw** [KHKKhalid/SAMPBulletproof#38]
I've screen this when a round just ended, i've given a look in match.inc but all its ok in top players.. here is a screen of da bug http://i.imgur.com/jBftXNZ.png i've seen this only 1 time not more times

**Comment by khalidahmedshalabi** [comment]
Are you talking about the kill message on chat being under Top Players chunk?

**Comment by shendlaw** [comment]
yeah

**Comment by khalidahmedshalabi** [comment]
Most likely lag.
