### ISSUE TITLE
Player who crashes during base-startup doesn't get re-added properly

### ISSUE THREAD

**Issue by khalidahmedshalabi** [KHKKhalid/SAMPBulletproof#41]
This is old and known. If you time-out while round is starting, when you come back, you will spawn in wrong position (sometimes CP or enemy team's spawn position).

**Comment by khalidahmedshalabi** [comment]
Problem is most likely somewhere in `modules/src/match.inc` and/or `modules/src/player.inc`

**Comment by shendlaw** [comment]
didn't see you made it already ahah

**Comment by khalidahmedshalabi** [comment]
It needs some investigation though. I recommend starting with `LoadPlayerVariables` and `StorePlayerVariables`/`StorePlayerVariablesMin` in `modules/src/player.in`.
