### ISSUE TITLE
Duel is bugged

### ISSUE THREAD

**Issue by khalidahmedshalabi** [KHKKhalid/SAMPBulletproof#42]
Sometimes duelers get stuck at duel arena after killing each other. The duel never ends then.

**Comment by fedfomin** [comment]
I tried do something and it's fine, if your opponent die you will respawn in lobby or in a main-spawn. But can't find that error: http://i.imgur.com/38e3cpn.png, i think its a problem with getplayerpos or cordinates correlated with x y and z i guess.

**Comment by 23Wallenstein** [comment]
i continue investigate

**Comment by 23Wallenstein** [comment]
*find

**Comment by khalidahmedshalabi** [comment]
Your tests were on a home server? I think it only happens on real hosted servers.

**Comment by 23Wallenstein** [comment]
I tested it on a home server and in a real hosted server, same thing

**Comment by 23Wallenstein** [comment]
\Bulletproof-Gamemode\pawno\include\modules\src\duel.inc i think there are a problem with getplayerpos

**Comment by 23Wallenstein** [comment]
maybe.
