### ISSUE TITLE
Global chat for all servers

### ISSUE THREAD

**Issue by khalidahmedshalabi** [KHKKhalid/SAMPBulletproof#47]
Connect all Bulletproof servers through one global chat system. I'm not sure how I'd make this bandwidth-friendly though.

**Comment by A-Gebrel** [comment]
Using IRC functions could solve it I guess, however, I wonder how you would prevent everyone from using it :V

**Comment by khalidahmedshalabi** [comment]
Why would I do that?

**Comment by A-Gebrel** [comment]
@KHKKhalid to keep it bandwidth friendly ? :V

**Comment by khalidahmedshalabi** [comment]
https://github.com/KHKKhalid/SAMPMatchFinder
