### ISSUE TITLE
Global banning

### ISSUE THREAD

**Issue by khalidahmedshalabi** [KHKKhalid/SAMPBulletproof#5]
A ban system (based on AC:GetPlayerHardwareID) connected to our MySQL database so bans are globalized and servers (Bulletproof ones) are under control.

**Comment by khalidahmedshalabi** [comment]
Would you still want this? @Whitetigerswt

**Comment by Whitetigerswt** [comment]
Yeah I mean that'd be cool but I don't have any way to determine (especially since the game mode is open source) that the bans are real

**Comment by khalidahmedshalabi** [comment]
Unfortunately, the only way I could think of is making the AC part close source, just like league. Though I'm not sure that would make it 100% secure/reliable (league isn't).
