### ISSUE TITLE
Bug on /admins

### ISSUE THREAD

**Issue by shendlaw** [KHKKhalid/SAMPBulletproof#56]
see what happens if there is more than 9 admins http://i.imgur.com/UQ0ZUn9.png

**Comment by OrdeneauxBiggar377** [comment]
Should be fixed with extending the String, or just using another Dialog Style. 
(Is there any other way to give you the code except with pastebin @KHKKhalid ? )

http://pastebin.com/rVpnCmdh

**Comment by khalidahmedshalabi** [comment]
Fork, fix it and then make a pull request @JustMe77
