### ISSUE TITLE
IsACEnabled bug

### ISSUE THREAD

**Issue by khalidahmedshalabi** [KHKKhalid/SAMPBulletproof#57]
> 6:41PM
> 
> Hi man
> Cant see vehicles on minimap (radar)
> As defender
> /config and Defender can see vehicles blips [Disable]
> its green
> but when I click on it its giving ERROR and write - Anticheat is not enabled
> But is enabled.. unsure emoticon

I could confirm this. There seems to be a problem with `IsACEnabled`. Here's code from gamemode:

``` C++
if(!IsACPluginLoaded())
{
    SendErrorMessage(playerid, "Anticheat plugin is not loaded.", MSGBOX_TYPE_BOTTOM);
    ShowConfigDialog(playerid);
}
else if(!IsACEnabled())
{
    SendErrorMessage(playerid, "Anticheat is not enabled.", MSGBOX_TYPE_BOTTOM);
    ShowConfigDialog(playerid);
}
else
{
    if(DefendersSeeVehiclesBlips == false)
    {
        DefendersSeeVehiclesBlips = true;
        format(iString, sizeof(iString), "{FFFFFF}%s "COL_PRIM"has {FFFFFF}enabled "COL_PRIM"defenders see vehicle blips{FFFFFF} option.", Player[playerid][Name]);
        SendClientMessageToAll(-1, iString);
    }
    else
    {
        DefendersSeeVehiclesBlips = false;
        format(iString, sizeof(iString), "{FFFFFF}%s "COL_PRIM"has {FFFFFF}disabled "COL_PRIM"defenders see vehicle blips{FFFFFF} option.", Player[playerid][Name]);
        SendClientMessageToAll(-1, iString);
    }
}
```

Screenshot: ![sa-mp-009](https://cloud.githubusercontent.com/assets/4519116/12124469/617e9646-b3ee-11e5-8300-f6524952fc45.png)

**Comment by Whitetigerswt** [comment]
Odd, are you sure it's enabled in `ac_config.ini`?

**Comment by khalidahmedshalabi** [comment]
Check the screenshot; it's enabled.

**Comment by khalidahmedshalabi** [comment]
Try to work out this problem (perhaps by the end of this month) because I have a few plans for AC on future versions of this gamemode and that's gonna disturb.

**Comment by khalidahmedshalabi** [comment]
Fixed it myself check the ac repo @Whitetigerswt
