### ISSUE TITLE
Lag Compensation & AntiCbug

### ISSUE THREAD

**Issue by ghost** [KHKKhalid/SAMPBulletproof#63]
Hello,
The lag compensation doesn't seem to be working properly, sometimes players don't take direct hits, even though I enabled lag compensation in server configuration - what should I do?
Also, could you please add /anticbug (in-game command) so we can enable/disable anticbug in-game for RC mode only (/start RC) that would be really great and helpful
Please and thanks.

**Comment by khalidahmedshalabi** [comment]
You have `anticbug.amx` in filterscripts folder.

**Comment by ghost** [comment]
Yeah, I know about that mate, but the problem is that anticbug is enabled everywhere not just RC, even in base modes and lobby, it shouldn't be like that cuz we can't have some fun base matches (/start base id) with cbug, it should be enabled for RC mode (/start RC) only and there should be a cmd to toggle it (/anticbug)
Thanks for the quick reply

**Comment by ghost** [comment]
https://youtu.be/9qqCrmvX8fo
that's the lag compensation thing I'm talking about, I recorded it
''The lag compensation doesn't seem to be working properly, sometimes players don't take direct hits, even though I enabled lag compensation in server configuration''

**Comment by khalidahmedshalabi** [comment]
Okay.

**Comment by ghost** [comment]
any update about this? c: when will they be fixed/added?

**Comment by khalidahmedshalabi** [comment]
Very soon.

**Comment by ghost** [comment]
anything yet?
