### ISSUE TITLE
/teamskin

### ISSUE THREAD

**Issue by ghost** [KHKKhalid/SAMPBulletproof#66]
make it if used like this
/teamskin 0 (it opens menu and you select)
if used like this 
/teamskin 0 230 (it sets skin directly)
simple suggestion
and please make an update to fix the bugs I reported, I need the server for my clan

**Comment by khalidahmedshalabi** [comment]
I will just make a pre-release version of the latest changes if I find myself taking too long to release the official update, so don't worry.
