### ISSUE TITLE
this server is not using the correct database. Visit www.bulletproof.ml for further help! samp

### ISSUE THREAD

**Issue by ghost** [KHKKhalid/SAMPBulletproof#68]
i already have the last .db in github

**Comment by khalidahmedshalabi** [comment]
I noticed this once as well. I think you can safely ignore this warning as long as everything is working fine. Of course this bug will be fixed in future versions.

**Comment by mrw77** [comment]
Alright, i thought it was serious error :D

**Comment by Tadas3333** [comment]
Fixed in my version.
