### ISSUE TITLE
SetPlayerSkin causes random crash

### ISSUE THREAD

**Issue by Tadas3333** [KHKKhalid/SAMPBulletproof#70]
SetPlayerSkin should be replaced with SetSpawnInfo and SpawnPlayer functions.

**Comment by khalidahmedshalabi** [comment]
Post the code you wrote for this cause it might help later.

**Comment by Tadas3333** [comment]
http://pastebin.com/ju9qut82

**Comment by Tadas3333** [comment]
Fixed in my version.
