### ISSUE TITLE
Connect all servers who run this gamemode

### ISSUE THREAD

**Issue by Tadas3333** [KHKKhalid/SAMPBulletproof#72]
Would be nice if we connected all servers with this gm. For example, store all match scores in a website (could use sampcup.com), and then make a timer that checks if there are new rows in a database, and if so, send message to all players. (For example: AsD won against RQe 4-3). 

Also we can implement global gamemode chat, that you can speak with other players who are in a server with this gamemode (you can ask for tcw for example.)

**Comment by khalidahmedshalabi** [comment]
This is the goal of league mode.

**Comment by mmiguerodriguez** [comment]
I saw a game mode which had it, wasn't it this one?

**Comment by khalidahmedshalabi** [comment]
Probably. Was it a Spanish server?

**Comment by Tadas3333** [comment]
https://s29.postimg.org/vljhbzblj/sa_mp_023.png
Made it (don't mind the scores lol), and seems like league has something similar already, but it's done not in a sexy way

**Comment by mmiguerodriguez** [comment]
Yeah, Spanish server @Khalid

**Comment by khalidahmedshalabi** [comment]
Yeah, yours looks better. I'll show you what's already done, so you can modify. @beijind
