### ISSUE TITLE
How to use skin shot?

### ISSUE THREAD

**Issue by Jinz0r** [KHKKhalid/SAMPBulletproof#78]
What is the command?

**Comment by khalidahmedshalabi** [comment]
https://wiki.sa-mp.com/wiki/Server.cfg#Lag_compensation

**Comment by Jinz0r** [comment]
This is the samp skin shot it sucks  . I want a skin shot equal white tiger old GM /nolag its possible?

**Comment by khalidahmedshalabi** [comment]
I remember removing that since nobody complained about `lagcompmode`. The gamemode is open source so if you're a coder you can do whatever you want with it.

**Comment by khalidahmedshalabi** [comment]
I remember removing that since nobody complained about lag comp. The gamemode is open source so if you're a coder you can do whatever you want with it.
